package workspace

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// CommonState describes the project's checkout of the common library.
type CommonState struct {
	Dir     string
	Version string // what HEAD is: a tag name, or a short commit
	Dirty   bool   // uncommitted changes in the checkout
	Want    string // the team's version
}

// InLine reports whether the checkout is exactly the team's version.
func (s CommonState) InLine() bool { return !s.Dirty && s.Version == s.Want }

// SyncCommon makes <project>/common a checkout of the common library at the
// team's version (a tag), cloning or fetching as needed.
//
// Together with go.work this is what lets "go to definition" land in the
// project's own common/ directory while builds stay identical to CI: the
// directory holds exactly the released version the services pin, not whatever
// main happens to be.
//
// A checkout with local changes is left alone, because devkit never discards
// someone's work; the caller is told through the returned state so it can warn
// that builds on this machine now differ from everyone else's.
func SyncCommon(ctx context.Context, dir, url, version, token, tokenHost string, log func(string, ...any)) (CommonState, error) {
	st := CommonState{Dir: dir, Want: version}
	if err := EnsureRepo(ctx, dir, url, token, tokenHost, func(string, ...any) {}); err != nil {
		return st, err
	}
	if out, err := git(ctx, dir, "", "fetch", "--quiet", "--tags", "origin"); err != nil {
		log("warning: could not fetch %s (%v): %s", dir, err, strings.TrimSpace(out))
	}
	st = CommonStatus(ctx, dir, version)
	switch {
	case st.Dirty:
		return st, nil
	case st.Version == version:
		log("common/ is at %s", version)
		return st, nil
	}
	if out, err := git(ctx, dir, "", "checkout", "--quiet", "--detach", version); err != nil {
		return st, fmt.Errorf("common/: cannot check out %s: %v: %s", version, err, strings.TrimSpace(out))
	}
	log("common/ %s -> %s", st.Version, version)
	return CommonStatus(ctx, dir, version), nil
}

// CommonStatus inspects a checkout without changing it.
func CommonStatus(ctx context.Context, dir, want string) CommonState {
	st := CommonState{Dir: dir, Want: want}
	if out, err := git(ctx, dir, "", "status", "--porcelain"); err == nil && strings.TrimSpace(out) != "" {
		st.Dirty = true
	}
	if out, err := git(ctx, dir, "", "describe", "--tags", "--exact-match", "HEAD"); err == nil {
		st.Version = strings.TrimSpace(out)
	} else if out, err := git(ctx, dir, "", "rev-parse", "--short", "HEAD"); err == nil {
		st.Version = strings.TrimSpace(out)
	}
	return st
}

const goWorkMarker = "// Managed by devkit: regenerated by `devkit ngs` and `devkit update`."

// SyncGoWork writes <project>/go.work so that the Go tools and the IDE resolve
// the common library to ./common instead of the read-only module cache. It
// lists ./common (when present) and every service.
//
// go.work lives in the project directory, which is not a repository: it is
// per machine and never reaches CI or a Docker build, which keep using the
// versions in each service's go.mod. A go.work written by hand (without the
// marker) is never overwritten.
func SyncGoWork(project, goVersion string, services []string) (changed bool, err error) {
	path := filepath.Join(project, "go.work")
	old, readErr := os.ReadFile(path)
	if readErr == nil && !strings.Contains(string(old), goWorkMarker) {
		return false, fmt.Errorf("%s exists and was not written by devkit; add the services to it yourself (go work use ./<service>)", path)
	}
	var use []string
	if _, err := os.Stat(filepath.Join(project, "common", "go.mod")); err == nil {
		use = append(use, "./common")
	}
	for _, s := range services {
		if _, err := os.Stat(filepath.Join(s, "go.mod")); err == nil {
			use = append(use, "./"+filepath.Base(s))
		}
	}
	if len(use) == 0 {
		return false, nil
	}
	sort.Strings(use)
	var b strings.Builder
	b.WriteString(goWorkMarker + "\n")
	b.WriteString("//\n// It makes \"go to definition\" open the project's own common/ directory, which\n")
	b.WriteString("// devkit keeps at the team's released version. It exists only on this machine;\n")
	b.WriteString("// CI and Docker builds use the versions in each service's go.mod.\n")
	b.WriteString("// GOWORK=off makes a command ignore it.\n\n")
	b.WriteString("go " + goVersion + "\n\nuse (\n")
	for _, u := range use {
		b.WriteString("\t" + u + "\n")
	}
	b.WriteString(")\n")
	if string(old) == b.String() {
		return false, nil
	}
	return true, os.WriteFile(path, []byte(b.String()), 0o644)
}
