package lock

import (
	"os"
	"path/filepath"
	"testing"
)

func write(t *testing.T, root, rel, content string) {
	t.Helper()
	p := filepath.Join(root, rel)
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func TestLockUnlock(t *testing.T) {
	root := t.TempDir()
	write(t, root, ".devkit/manifest.json", `{"schema":1,"components":{"kitex-service":{"version":"1","files":{"Makefile":"sha256:x","cmd/svc/main.go":"sha256:y"}}}}`)
	write(t, root, "Makefile", "all:\n")
	write(t, root, "cmd/svc/main.go", "package main\n")
	write(t, root, "cmd/svc/openapi.yaml", "openapi: 3.0.0\n")
	write(t, root, "kitex_gen/a/a.go", "package a\n")
	write(t, root, "router/svc/svc.go", "// Code generated by hertz generator. DO NOT EDIT.\n\npackage svc\n")
	write(t, root, "router/svc/middleware.go", "// Code generated by hertz generator.\n\npackage svc\n")
	write(t, root, "handler/handler.go", "package handler\n")
	write(t, root, "idl.lock", "abc\n")

	files, err := Files(root)
	if err != nil {
		t.Fatal(err)
	}
	want := []string{".devkit/manifest.json", "Makefile", "cmd/svc/main.go", "cmd/svc/openapi.yaml", "idl.lock", "kitex_gen/a/a.go", "router/svc/svc.go"}
	if len(files) != len(want) {
		t.Fatalf("files = %v, want %v", files, want)
	}
	for i := range want {
		if files[i] != want[i] {
			t.Fatalf("files = %v, want %v", files, want)
		}
	}

	n, err := Lock(root)
	if err != nil || n != len(want) {
		t.Fatalf("Lock = %d, %v", n, err)
	}
	for _, rel := range want {
		st, _ := os.Stat(filepath.Join(root, rel))
		if st.Mode().Perm()&0o222 != 0 {
			t.Fatalf("%s still writable: %v", rel, st.Mode())
		}
	}
	for _, rel := range []string{"handler/handler.go", "router/svc/middleware.go"} {
		st, _ := os.Stat(filepath.Join(root, rel))
		if st.Mode().Perm()&0o200 == 0 {
			t.Fatalf("%s should stay writable", rel)
		}
	}
	if n, _ := Lock(root); n != 0 {
		t.Fatalf("second Lock changed %d files", n)
	}
	n, err = Unlock(root)
	if err != nil || n != len(want) {
		t.Fatalf("Unlock = %d, %v", n, err)
	}
	st, _ := os.Stat(filepath.Join(root, "Makefile"))
	if st.Mode().Perm()&0o200 == 0 {
		t.Fatal("Makefile not writable after Unlock")
	}
}
